[package]
name = "spider-novel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.11"
tokio = {version = "1.0.0", features = ["full"]}
anyhow = "1.0.58"
scraper = "0.13.0"
chrono = "0.4.19"
static_init = "1.0.2"
[dev-dependencies]
tokio-test = "0.4.2"
