[package]
name = "spider-novel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.11"
tokio = { version = "1.0.0", features = ["full"] }
anyhow = "1.0.58"
scraper = "0.13.0"
chrono = "0.4.19"
static_init = "1.0.2"
log = "0.4"
fast_log = "1.5.17"
serde = "1.0.137"
async-trait = "0.1.56"
rs-snowflake = "0.6.0"
[dependencies.sea-orm]
version = "0.8.0"
features = [
    "macros",
    "with-chrono",
    "sqlx-sqlite",
    "runtime-tokio-native-tls"
]
[dev-dependencies]
tokio-test = "0.4.2"
